In [1]:
import pandas as pd

df_angajati = pd.DataFrame({
    'nume': ['Andrei', 'Elena', 'Radu', 'Ioana', 'Mihai', 'Alina'],
    'departament': ['HR', 'IT', 'IT', 'Marketing', 'IT', 'HR'],
    'experienta_ani': [2, 5, 1, 8, 10, None], # Alina e nou angajată, datele lipsesc
    'salariu': [4000, 8500, 3500, 6000, 12000, 4200],
    'bonus_primit': ['Da', 'Nu', 'Nu', 'Da', 'Da', 'Nu']
})

In [2]:
df_angajati['experienta_ani'] = df_angajati['experienta_ani'].fillna(0)

In [3]:
df_angajati['experienta_ani']

0     2.0
1     5.0
2     1.0
3     8.0
4    10.0
5     0.0
Name: experienta_ani, dtype: float64

In [4]:
df_angajati['bonus_primit'] = df_angajati['bonus_primit'].map({'Da':1, 'Nu': 0})

In [5]:
df_angajati['bonus_primit']

0    1
1    0
2    0
3    1
4    1
5    0
Name: bonus_primit, dtype: int64

In [6]:
df_angajati.groupby('departament').agg({
    'departament': 'IT',
    'salariu': 'mean'
})

AttributeError: 'SeriesGroupBy' object has no attribute 'IT'

In [ ]:
df_angajati[df_angajati['departament'] == 'IT']['salariu'].mean()

In [ ]:
ang_exp = df_angajati[(df_angajati['experienta_ani'] > 4) & (df_angajati['bonus_primit']==1)]
ang_exp

In [ ]:
import pandas as pd

# Tabelul cu detaliile clienților (Atenție la spațiile din numele Anei și al lui Carmen)
df_clienti = pd.DataFrame({
    'id_client': [1, 2, 3, 4],
    'nume': ['  Ana ', 'Bogdan', '  Carmen  ', 'Dan'],
    'oras': ['Bucuresti', 'Cluj', 'Iasi', 'Timisoara']
})

# Tabelul cu achizițiile (Dan, clientul 4, nu a cumpărat nimic încă)
df_comenzi = pd.DataFrame({
    'id_comanda': [101, 102, 103, 104, 105],
    'id_client': [1, 1, 2, 3, 2],
    'produs': ['Laptop', 'Mouse', 'Monitor', 'Tastatura', 'Casti'],
    'pret': [4500, 150, 1200, 300, 400]
})

In [ ]:
df_final = pd.merge(df_clienti, df_comenzi, how='outer', on='id_client')

In [ ]:
df_final

In [ ]:
df_final['nume'] = df_final['nume'].str.strip()
df_final

In [ ]:
df_final['pret'] = df_final['pret'].fillna(0)

In [ ]:
df_final.groupby('oras').agg({
    'pret': 'sum'
})

In [ ]:
import pandas as pd

# Un tabel simplu de vânzări cu date calendaristice sub formă de text
df_vanzari = pd.DataFrame({
    'data_tranzactie': ['2023-12-01', '2023-12-15', '2024-01-10', '2024-01-22'],
    'client': ['Ana', 'Bogdan', 'Ana', 'Dan'],
    'suma': [150, 200, 350, 400]
})

In [ ]:
df_vanzari['data_tranzactie'] = pd.to_datetime(df_vanzari['data_tranzactie'])

In [ ]:
df_vanzari['luna'] = df_vanzari['data_tranzactie'].dt.month

In [ ]:
df_vanzari.to_csv('raport_vanzari.csv', index = False)